### ISSUE TITLE
Mobile hold n drag API for DFOnline does not delete block after dragging

### ISSUE THREAD

**Issue by UserUNP** [GeorgeRNG/dfonline#14]
Reproduce:
- have a phone
- have internet connection
- sit on a chair and lay back
- be curious and look up dfonline.dev on Chrome on your phfone (very important)
- create new template
- drag stuff
- drag more stuff
- try to move stuff

eExpectation:
move stuff.

Reality:
duplicates stuff.

**Comment by GeorgeRNG** [comment]
Affects touch simulation on chromium based browsers
